// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package persistence

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
}

type Post struct {
	ID          uuid.UUID    `json:"id"`
	Title       string       `json:"title"`
	Slug        string       `json:"slug"`
	Content     string       `json:"content"`
	AuthorID    uuid.UUID    `json:"author_id"`
	Status      string       `json:"status"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	PublishedAt sql.NullTime `json:"published_at"`
}

type PostCategory struct {
	PostID     uuid.UUID `json:"post_id"`
	CategoryID int32     `json:"category_id"`
}

type User struct {
	ID        uuid.UUID   `json:"id"`
	Username  string      `json:"username"`
	Email     string      `json:"email"`
	Password  string      `json:"password"`
	Role      string      `json:"role"`
	CreatedAt time.Time   `json:"created_at"`
	Posts     []uuid.UUID `json:"posts"`
}
