// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package persistence

import (
	"database/sql"
	"time"
)

type Category struct {
	ID        int32
	Name      string
	Slug      string
	CreatedAt time.Time
}

type Post struct {
	ID          int32
	Title       string
	Content     string
	AuthorID    int32
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	PublishedAt sql.NullTime
}

type PostCategory struct {
	PostID     int32
	CategoryID int32
}

type User struct {
	ID        int32
	Username  string
	Email     string
	Password  string
	Role      string
	CreatedAt time.Time
	Posts     []int32
}
