// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package persistence

import (
	"context"

	"github.com/google/uuid"
)

//go:generate mockgen -source=querier.go -destination=mocks/querier_mock.go
type Querier interface {
	CreateContent(ctx context.Context, arg CreateContentParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetContent(ctx context.Context, id uuid.UUID) (Post, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListContents(ctx context.Context) ([]Post, error)
	ListContentsWithCategories(ctx context.Context) ([]PostView, error)
	ListUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
